### ISSUE TITLE
I have question. I think this code have security risk

### ISSUE THREAD

**Issue by PeterTakahashi** [q9f/ethereum-on-rails#11]
When signup, is it possible to send eth addresses other than my own from the front end to the back end?

I think that since the app/javascript/packs/users_new.js puts your address into the form on the front side, the backend side cannot determine if this is really the address of the user who submitted the post.

**Comment by q9f** [comment]
Yes, that is correct. I wrote about it here: https://dev.to/q9/finally-authenticating-rails-users-with-metamask-3fj

![Screenshot_20220417-190814.png](https://user-images.githubusercontent.com/58883403/163725073-07659a92-7d70-47bc-9ac0-274a753966c0.png)

In production, user_new and session_new should be coupled and always require a signature.

I decoupled it for educational purposes but it should really only be one process:

1. Connect to MetaMask
2. Request accounts
3. Check if account exists
   - if true, require signature and log in
   - if false, require signature, create user, and log in

If anyone wants to submit a PR, I'm happy to consider it.

**Comment by q9f** [comment]
Also, I want to emphasize that this is not intended for production whatsoever!

![Screenshot_20220417-194458.png](https://user-images.githubusercontent.com/58883403/163726246-764ac4ed-380d-45e9-868f-e1f2d87320d6.png)

Please use the amazing SIWE libraries linked in the Readme!

**Comment by PeterTakahashi** [comment]
thank you for response.
sorry. I have not read that words.

> If anyone wants to submit a PR, I'm happy to consider it.

if I build signup feature, I gonna submit a PR
